version: "3.8"

services:
  postgres:
    image: bitnami/postgresql
    container_name: to-do-list
    # restart: always
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
